'''
To generate timeseries of 2-4 degC bottom habitat.

Uses pickled object generated by azmp_bottom_stats.py

'''

import numpy as  np
import matplotlib.pyplot as plt
import pandas as pd
import os

# plot tuning:
font = {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : 13}
plt.rc('font', **font)
width = 0.7

clim_year = [1991, 2020]

#### ------------- For fall ---------------- ####
# 1.
infile = 'operation_files/stats_2J_fall.pkl'
df = pd.read_pickle(infile)
df.index = pd.to_datetime(df.index) # update index to datetime
df = df['area_shrimp']
df = df/1000
df_clim = df[(df.index.year>=clim_year[0]) & (df.index.year<=clim_year[1])]
std_anom = (df-df_clim.mean(axis=0))/df_clim.std(axis=0)
std_anom2J = std_anom

# 2.
infile = 'operation_files/stats_3K_fall.pkl'
df = pd.read_pickle(infile)
df.index = pd.to_datetime(df.index) # update index to datetime
df = df['area_shrimp']
df = df/1000
df_clim = df[(df.index.year>=clim_year[0]) & (df.index.year<=clim_year[1])]
std_anom = (df-df_clim.mean(axis=0))/df_clim.std(axis=0)
std_anom3K = std_anom


# 3.
infile = 'operation_files/stats_3LNO_fall.pkl'
df = pd.read_pickle(infile)
df.index = pd.to_datetime(df.index) # update index to datetime
df = df['area_shrimp']
df = df/1000
df_clim = df[(df.index.year>=clim_year[0]) & (df.index.year<=clim_year[1])]
std_anom = (df-df_clim.mean(axis=0))/df_clim.std(axis=0)
std_anom3LNO = std_anom


# 4. plot all merged together
std_anom_all = pd.concat([std_anom2J, std_anom3K, std_anom3LNO], axis=1)
df = std_anom_all.mean(axis=1)
df.index = df.index.year

fig = plt.figure(4)
fig.clf()
sign=df>0
df.plot(kind='bar', color=sign.map({True: 'indianred', False: 'steelblue'}), width = width)
plt.ylabel('Mean Standardized Anomaly', weight='bold', fontsize=14)
#plt.xlabel('Year')
plt.title(r'2-4$\rm ^{\circ}C$ Habitat anomaly for 2J3KLNO - Fall', weight='bold', fontsize=14)
plt.grid()
plt.ylim([-2.5,2.5])
#plt.gca().set_xlim([pd.to_datetime('1979-01-01'), pd.to_datetime('2018-01-01')]) 
fig.set_size_inches(w=15,h=7)
fig_name = 'shrimp_habitat_anomalies_fall.png'
fig.savefig(fig_name)
os.system('convert -trim shrimp_habitat_anomalies_fall.png shrimp_habitat_anomalies_fall.png')




#### ------------- For Spring ---------------- ####
# 1.
infile = 'operation_files/stats_3LNO_spring.pkl'
df = pd.read_pickle(infile)
df.index = pd.to_datetime(df.index) # update index to datetime
df = df['area_shrimp']
df = df/1000
df_clim = df[(df.index.year>=clim_year[0]) & (df.index.year<=clim_year[1])]
std_anom = (df-df_clim.mean(axis=0))/df_clim.std(axis=0)
std_anom3LNO = std_anom

# 2.
infile = 'operation_files/stats_3Ps_spring.pkl'
df = pd.read_pickle(infile)
df.index = pd.to_datetime(df.index) # update index to datetime
df = df['area_shrimp']
df = df/1000
df_clim = df[(df.index.year>=clim_year[0]) & (df.index.year<=clim_year[1])]
std_anom = (df-df_clim.mean(axis=0))/df_clim.std(axis=0)
std_anom3Ps = std_anom

# 4. plot all merged together
std_anom_all = pd.concat([std_anom3LNO, std_anom3Ps], axis=1)
df = std_anom_all.mean(axis=1)
df.index = df.index.year


fig = plt.figure(5)
fig.clf()
sign=df>0
#df.plot(kind='bar', color=sign.map({True: 'darkorange', False: 'steelblue'}), width = width)
df.plot(kind='bar', color=sign.map({True: 'indianred', False: 'steelblue'}), width = width)
plt.ylabel('Mean Standardized Anomaly', weight='bold', fontsize=14)
#plt.xlabel('Year')
plt.title(r'2-4$\rm ^{\circ}C$ Habitat anomaly for 3LNOPs - Spring', weight='bold', fontsize=14)
plt.grid()
plt.ylim([-2.5,2.5])
#plt.gca().set_xlim([pd.to_datetime('1979-01-01'), pd.to_datetime('2018-01-01')]) 
fig.set_size_inches(w=15,h=7)
fig_name = 'shrimp_habitat_anomalies_spring.png'
fig.savefig(fig_name)
os.system('convert -trim shrimp_habitat_anomalies_spring.png shrimp_habitat_anomalies_spring.png')

